services:
  fenicsxtutorial:
    image: fenicsxtutorial
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
      - ./src:/root/workspace/src
    command: ["sleep", "infinity"]